### ISSUE TITLE
PushNotificationManager Error

### ISSUE THREAD

**Issue by gamble86** [OutSystems/OutSystemsNow-iOS#1]
Hi all,

I downloaded the files, have not edited a single file, open it up in xcode and run it. 
The build fails with an error, "OutsystemsAppDelegate.h" , "Pushwoosh/PushNotification Manager.h" file not found.

**Comment by luissilvaos** [comment]
Hi @gamble86 
I did the same here and everything worked for me. 
Which target have you selected for building the project?
